geekshop/adminapp/urls.py
from django.urls import path
from adminapp import views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.user_create, name='user_create'),
    path('users/read/', adminapp.user_read, name='user_read'),
    path('users/update/<pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<pk>/', adminapp.user_delete, name='user_delete'),

    path('categories/create', adminapp.category_create, name='category_create'),
    path('categories/read/', adminapp.category_read, name='category_read'),
    path('categories/update/<pk>/', adminapp.category_update, name='category_update'),
    path('categories/delete/<pk>/', adminapp.category_delete, name='category_delete'),
    #
    path('categories/products/read/<pk>', adminapp.products_read, name='products_read'),
#    path('products/create/<pk>/', adminapp.product_create, name='product_create'),
#    path('products/update/<pk>/', adminapp.product_update, name='product_update'),
#    path('products/delete/<pk>/', adminapp.product_delete, name='product_delete'),
#    path('products/detail/<pk>/', adminapp.product_detail, name='product_detail'),


]

geekshop/authapp/urls.py
from django.urls import path
from authapp.views import login, logout, register, edit

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

geekshop/basketapp/urls.py
from django.urls import path
from basketapp.views import basket_add, basket_list, basket_remove, basket_edit
app_name = 'basket'

urlpatterns = [
    path('', basket_list, name='list'),
    path('add/<pk>/', basket_add, name='add'),
    path('remove/<pk>/', basket_remove, name='remove'),
    path('edit/<pk>/<quantity>/', basket_edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
from mainapp import views

from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
#import mainapp.views
urlpatterns = [
    #path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='adminapp')),
    path('', views.index, name="index"),
    path('contact/', views.contact, name="contact"),
    path('products/', include('mainapp.urls', namespace="products")),
    path('auth/', include('authapp.urls', namespace="authapp")),
    path('basket/', include('basketapp.urls', namespace="basket")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path
from mainapp.views import products, product
app_name = 'products'

urlpatterns = [
    path('', products, name='products_hot_product'),
    path('<int:pk>/', products, name='product_list'),
    path('product/<int:pk>/', product, name='product_item'),
]

geekshop/mainapp/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=128, verbose_name='название', unique=True)
    description = models.TextField(verbose_name='описание')
    is_active = models.BooleanField(default=True, verbose_name='Активен')
    def __str__(self):
        return f'#{self.pk}. {self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('name', )

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория')
    name = models.CharField(max_length=128, verbose_name='название', unique=True)
    image = models.ImageField(upload_to='product', blank=True, null=True, verbose_name='изображение')
    short_desc = models.CharField(max_length=128, verbose_name='краткое описание')
    description = models.TextField(max_length=128, verbose_name=' полное описание')
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='цена')
    quantity =models.PositiveSmallIntegerField(default=0, verbose_name='количество')
    is_active = models.BooleanField(default=True, verbose_name='Активен')
    def __str__(self):
        return f'{self.name} ({self.category.name})'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

geekshop/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from mainapp.models import Product, Category
from basketapp.models import Basket
from mainapp.services import get_basket, get_same_products, get_hot_product




def index(request):
    context = {
        'products': Product.objects.all()[:4],
        'basket': get_basket(request.user)
    }
    return render(request, 'mainapp/index.html', context)
# Create your views here.

def products(request, pk=None):
    print(pk)
    links_menu = Category.objects.all()


    if pk is not None:
        if pk == 0:
            products_list = Product.objects.all()
            category_item = {'name' : 'все', 'pk' : 0}
        else:
            category_item = get_object_or_404(Category, pk=pk)
            products_list = Product.objects.filter(category_id=pk)

        context = {
            'links_menu' : links_menu,
            'products' : products_list,
            'category' : category_item,
            'basket' : get_basket(request.user)
              }
        return render(request, 'mainapp/products_list.html', context)


    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    context = {
        'links_menu': links_menu,
        'basket': get_basket(request.user),
        'hot_product': hot_product,  ####correct
        'same_products': same_products  ####correct
    }
    return render(request, 'mainapp/products.html', context)

def product(request, pk):
    product_item = get_object_or_404(Product, pk=pk)
    context = {
        'links_menu': Category.objects.all(),
        'product': product_item,
        'basket': get_basket(request.user),
    }
    return render(request, 'mainapp/product.html', context)

def contact(request):
    context = {
        'basket': get_basket(request.user)
    }
    return render(request, 'mainapp/contact.html')

geekshop/mainapp/templates/mainapp/includes/inc_main_menu.html
<a href="{% url 'index' %}" class="logo"></a>
<ul class="menu">
    <li><a href="{% url 'index' %}" {% if request.resolver_match.url_name == 'index' %}class="active"{% endif %}>домой</a></li>
    <li><a href="{% url 'products:products_hot_product' %}" {% if request.resolver_match.url_name == 'products' %}class="active"{% endif %}>продукты</a></li>
    <li><a href="{% url 'contact' %}" {% if request.resolver_match.url_name == 'contact' %}class="active"{% endif %}>контакты</a></li>
    {% if user.is_authenticated %}
        {% if user.is_superuser %}
            <li>
                <a href="{% url 'adminapp:user_read' %}">Админка </a>
            </li>
        {% endif %}
        <li>
            <a href="{% url 'authapp:edit' %}">{{user.first_name|default:'Пользователь'}}</a>
        </li>
        <li>
            <a href="{% url 'authapp:logout' %}">выход</a>
        </li>
    {% else %}
        <li>
            <a href="{% url 'authapp:login' %}">вход</a>
        </li>
    {% endif %}
</ul>
<a href="#" class="search"></a>
<a href="{% url 'basket:list' %}" class="basket">
    <span style="display: block; margin-left: 30px; color: black">
        {% if basket %}
            {{ basket.0.total_cost|floatformat:0 }} руб<br>
            ({{ basket.0.total_quantity }} шт)
        {% endif %}
    </span>
</a>

geekshop/mainapp/templates/mainapp/includes/inc_products_menu.html
<ul class="links-menu">

        <li>
            <a href="{% url 'products:product_list' 0 %}"
            {% if request.resolver_match.kwargs.pk == 0 %}class="active"{% endif %}>
                все
            </a>
        </li>
    {% for link_menu in links_menu %}
        <li>
            <a href="{% url 'products:product_list' link_menu.pk %}"
               {% if request.resolver_match.kwargs.pk == link_menu.pk %}class="active"{% endif %}>

                {{link_menu.name}}
            </a>
        </li>
    {% endfor %}
</ul>