geekshop/adminapp/urls.py
from django.urls import path
from adminapp import views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.user_create, name='user_create'),
    path('users/read/', adminapp.user_read, name='user_read'),
    path('users/update/<pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<pk>/', adminapp.user_delete, name='user_delete'),

    path('categories/create', adminapp.category_create, name='category_create'),
    path('categories/read/', adminapp.category_read, name='category_read'),
    path('categories/update/<pk>/', adminapp.category_update, name='category_update'),
    path('categories/delete/<pk>/', adminapp.category_delete, name='category_delete'),
    #
    path('categories/products/read/<pk>', adminapp.products_read, name='products_read'),
#    path('products/create/<pk>/', adminapp.product_create, name='product_create'),
#    path('products/update/<pk>/', adminapp.product_update, name='product_update'),
#    path('products/delete/<pk>/', adminapp.product_delete, name='product_delete'),
#    path('products/detail/<pk>/', adminapp.product_detail, name='product_detail'),


]

geekshop/authapp/urls.py
from django.urls import path
from authapp.views import login, logout, register, edit

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
from mainapp import views

from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
#import mainapp.views
urlpatterns = [
    #path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='adminapp')),
    path('', views.index, name="index"),
    path('contact/', views.contact, name="contact"),
    path('products/', include('mainapp.urls', namespace="products")),
    path('auth/', include('authapp.urls', namespace="authapp")),
    path('basket/', include('basketapp.urls', namespace="basket")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

geekshop/adminapp/models.py
from django.db import models

# Create your models here.

geekshop/adminapp/forms.py
from authapp.forms import ShopUserEditForm
from authapp.models import ShopUser
from django import forms
from mainapp.models import Product
class UserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'

class ProductEditForm(forms.ModelForm):

    class Meta:
        model = Product
        #fields = '__all__'
        exclude = ('is_active',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

geekshop/adminapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from adminapp.forms import UserAdminEditForm, ProductEditForm ##???
from authapp.forms import ShopUserEditForm
from django.contrib.auth.decorators import user_passes_test
from authapp.models import ShopUser
from mainapp.models import Product, Category


@user_passes_test(lambda u: u.is_superuser)
def user_create(request):
    return None

@user_passes_test(lambda u: u.is_superuser)
def user_read(request):
    context = {
        'objects': ShopUser.objects.all().order_by('-is_active', 'is_superuser')
    }
    return render(request, 'adminapp/user_list.html', context)

@user_passes_test(lambda u: u.is_superuser)
def user_update(request, pk):
    user_item = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        edit_form = UserAdminEditForm(request.POST, request.FILES, instance=user_item)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('adminapp:user_update', args=[pk]))
    else:
        edit_form = UserAdminEditForm(instance=user_item)


    context = {
        'form': edit_form

    }
    return render(request, 'adminapp/user_form.html', context)

@user_passes_test(lambda u: u.is_superuser)
def user_delete(request, pk):
    user_item = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        user_item.is_active = False
        user_item.save()
        return HttpResponseRedirect(reverse("adminapp:user_read"))
    context = {
        "object": user_item

    }
    return render(request, 'adminapp/user_delete_confirm.html', context)


def category_create(request):
    return None


def category_read(request):
    context = {
        'objects_list': Category.objects.all().order_by('-is_active')
    }
    return render(request, 'adminapp/category_list.html', context)

def category_update(request):
    return None

def category_delete(request):
    return None

def products_read(request, pk):
    category_item = get_object_or_404(Category, pk=pk)
    products_list = Product.objects.filter(category_id=pk)
    context = {
        'objects_list': products_list,
        'category': category_item
    }
    return render(request, 'adminapp/products_list.html', context)

def product_create(request, pk):
    category_item = get_object_or_404(Category, pk=pk)
    if request.method == 'POST':
        product_form = ProductEditForm(request.POST, request.FILES)
        if product_form.is_valid():
            product_item = product_form.save()
            return HttpResponseRedirect(reverse('adminapp:products_read', args=[product_item.category.pk]))

    else:
        product_form = ProductEditForm()
    context = {
        'form': product_form
    }
    return render(request, 'adminapp/product_form.html', context)

geekshop/adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
<div class="admin_container">
    <div class="h2 text-center head">
        Админка
    </div>
    {% block menu %}
    <div class="admin_menu">
        {% include 'adminapp/includes/inc_menu.html' %}
    </div>
    {% endblock %}
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

geekshop/adminapp/templates/adminapp/category_list.html
{% extends 'adminapp/base.html' %}

{% block content %}
<div class="categories_list">
    <button class="new_category">
        <a href={% url 'adminapp:category_create' %}>
        новая категория
        </a>
    </button>
    {% for object in objects_list %}
    <div class="category_record">
        <div class="category_name">
            {{ object.name|title }}
        </div>
        <div class="category_actions">
            <button>
                <a href="{% url 'adminapp:products_read' object.pk%}">
                товары категории
                </a>
            </button>
            <button>
                <a href="{% url 'adminapp:category_update' object.pk %}">
                редактировать
                </a>
            </button>
            <button>
                <a href="{% url 'adminapp:category_delete' object.pk %}">
                удалить
                </a>
            </button>
        </div>
        <div class="category_desc">
            {{ object.description|title }}
        </div>
    </div>
    {% endfor%}
</div>
{% endblock %}

geekshop/adminapp/templates/adminapp/product_form.html
{% extends 'adminapp/base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-3">
        <div class="col-md-6"></div>
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="form-control btn-primary">Сохранить</button>
        </form>
    </div>
</div>
{% endblock %}

geekshop/adminapp/templates/adminapp/products_list.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% block content %}
<div class="products_list">
    <button class="new_product">
        <a href="{% url 'adminapp:product_create' category.pk %}">
        новый продукт
        </a>
    </button>
    {% for object in objects_list %}
    <div class="product_record">
        <img
                src="/media/{{object.image|default:'products_images/default.jpg'}}"
                alt="{{ object.name }}">
        <div class="product_name">
            {{ object.name|title }}
        </div>
        <div class="product_actions">
            <button>
                <a href="#">
                подробнее
                </a>
            </button>
            <button>
                <a href="#">
                редактировать
                </a>
            </button>
            <button>
                <a href="#">
                удалить
                </a>
            </button>
        </div>
        <div class="summary">
            <b>цена</b>
            <p>{{ object.price }} руб</p>
            <b>количество</b>
            <p>{{ object.quantity }}</p>
        </div>
        <div class="product_desc">
            {{ object.short_desc|title }}
        </div>
    </div>
    {% endfor%}
</div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_delete_confirm.html
{% extends 'adminapp/base.html' %}

{% block content %}
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      Уверены, что хотите удалить пользователя {{ object.get_full_name }} ({{ object.username}})?
      <form method="post">
        {% csrf_token %}
        <button class="btn btn-danger">Уверен</button>
        <a class="btn btn-info" href="{% url 'adminapp:user_read' %}"Я передумал></a>
      </form>
    </div>
  </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_form.html
{% extends 'adminapp/base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-6">
        <div class="col-md-3"></div>
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="form-control btn-primary">Сохранить</button>
        </form>
    </div>
</div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_list.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% block content %}
<div class="users_list">
    <button class="new_user">
        <a href={% url 'adminapp:user_create' %}>
        новый пользователь
        </a>
    </button>
    {% for object in objects %}
    <div
            class="user_record {% if not object.is_active %}not_active{% endif %}">
        <img
                src="{% if object.avatar %}/media/{{ object.avatar }}{% else %}{% static 'img/default.jpg' %}{% endif %}"
                alt="{{ object.username }}">
        <div class="user_role">
            {% if object.is_superuser %}
            администратор
            {% else %}
            пользователь
            {% endif %}
            <button>
                <a href={% url 'adminapp:user_update' object.pk %}>
                редактировать
                </a>
            </button>
            <button>
                <a href={% url 'adminapp:user_delete' object.pk %}>
                удалить
                </a>
            </button>
        </div>
        <div class="user_name">
            <p><strong>{{ object.username }}</strong></p>
            <p>
                {{ object.get_full_name }}
            </p>
        </div>
        <div class="user_age">
            age:<br>
            {{ object.age }} лет
        </div>
        <div class="user_email">
            email:<br>
            {{ object.email }}
        </div>
        <div class="user_lastlogin">
            logged:<br>
            {{ object.last_login }}
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}