geekshop/authapp/urls.py
from django.urls import path
from authapp.views import login, logout, register, edit

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
from mainapp import views

from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
#import mainapp.views
urlpatterns = [
    #path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='adminapp')),
    path('', views.index, name="index"),
    path('contact/', views.contact, name="contact"),
    path('products/', include('mainapp.urls', namespace="products")),
    path('auth/', include('authapp.urls', namespace="authapp")),
    path('basket/', include('basketapp.urls', namespace="basket")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

geekshop/authapp/models.py
from django.db import models


from django.contrib.auth.models import AbstractUser, User
# Create your models here.

class ShopUser(AbstractUser):
    avatar = models.ImageField(upload_to='', blank=True, verbose_name='Аватарка')
    age = models.PositiveSmallIntegerField(verbose_name='Возраст')

geekshop/authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms
from authapp.models import ShopUser


class ShopUserLoginForm(AuthenticationForm):

    class Meta:
        model= ShopUser
        fields = ('username', 'password',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fild_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model= ShopUser
        fields = ('username', 'first_name', 'last_name', 'email', 'age', 'avatar', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fild_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def clean_age(self):
        current_age = self.cleaned_data['age']
        if current_age < 18:
            raise forms.ValidationError('Вы слишком молоды для этого')
        return current_age

class ShopUserEditForm(UserChangeForm):

    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'email', 'age', 'avatar', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()
    def clean_age(self):
        current_age = self.cleaned_data['age']
        if current_age < 18:
            raise forms.ValidationError('Вы слишком молоды для этого')
        return current_age

geekshop/authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from authapp.forms import ShopUserLoginForm, ShopUserRegisterForm, ShopUserEditForm
from django.contrib import auth
from django.urls import reverse

# Create your views here.
def login(request):
    login_form = ShopUserLoginForm(data=request.POST)
    next_url = request.GET.get('next', '')
    if request.method == "POST" and login_form.is_valid():
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            if 'next' in request.POST.keys():
                return HttpResponseRedirect(request.POST.get('next'))
            return HttpResponseRedirect(reverse('index'))

    context = {

                'form': login_form,
                'title': 'Вход в систему',
                'next': next_url
    }

    return render(request, 'authapp/login.html', context)

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('authapp:login'))
    else:
        register_form = ShopUserRegisterForm()

    context = {
        'form': register_form,
        'title': 'Регистрация'
    }

    return render(request, 'authapp/register.html', context)

def edit(request):
    if request.method == 'POST':
        edit_form = ShopUserEditForm(request.POST, request.FILES, instance=request.user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('authapp:edit'))
    else:
        edit_form = ShopUserEditForm(instance=request.user)

    context = {
        'form': edit_form,
        'title': 'Редактирование профиля'
    }
    return render(request, 'authapp/edit.html', context)

geekshop/authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
<div class="container">
    <div class="login" style="padding: 10px">
        <div class="h2 text-center head">
            {{ title }}
        </div>
        {% block content %}
        {% endblock %}
    </div>
</div>
</body>
</html>

geekshop/authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}

{% block content %}
    <form class="from-horizontal" method="post" action="{% url 'authapp:edit' %}"
          enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Сохранить</button>
        <a class="btn btn-info" href="{% url 'index' %}" style="...">На главную</a>
        <div class="user_avatar">
            <img src="/media/{{user.avatar}}"/>
        </div>>
    </form>
{% endblock %}

geekshop/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}

{% block content %}
 <!--   <form class="from-horizontal" method="post" action="{% url 'authapp:login' %}">    -->
    <form class="from-horizontal" method="post", action="{% url 'authapp:login' %}">
        {% csrf_token %}
        {% if next %}
            <input type="hidden" value="{{ next }}" name="next">
        {% endif %}
            <input type="hidden">
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Войти</button>
        <a class="btn btn-info" href="{% url 'authapp:register' %}" style="width: 100%">Зарегистрироваться</a>
    </form>
{% endblock %}

geekshop/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}

{% block content %}
    <form class="from-horizontal" method="post" action="{% url 'authapp:register' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Зарегистрироваться</button>
        <a class="btn btn-info" href="{% url 'authapp:login' %}" style="...">Войти</a>
    </form>
{% endblock %}