geekshop/authapp/urls.py
from django.urls import path
from authapp.views import login, logout, register, edit

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

geekshop/basketapp/urls.py
from django.urls import path
from basketapp.views import basket_add, basket_list, basket_remove, basket_edit
app_name = 'basket'

urlpatterns = [
    path('', basket_list, name='list'),
    path('add/<pk>/', basket_add, name='add'),
    path('remove/<pk>/', basket_remove, name='remove'),
    path('edit/<pk>/<quantity>/', basket_edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
from mainapp import views

from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
#import mainapp.views
urlpatterns = [
    #path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls', namespace='adminapp')),
    path('', views.index, name="index"),
    path('contact/', views.contact, name="contact"),
    path('products/', include('mainapp.urls', namespace="products")),
    path('auth/', include('authapp.urls', namespace="authapp")),
    path('basket/', include('basketapp.urls', namespace="basket")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path
from mainapp.views import products, product
app_name = 'products'

urlpatterns = [
    path('', products, name='products_hot_product'),
    path('<int:pk>/', products, name='product_list'),
    path('product/<int:pk>/', product, name='product_item'),
]

geekshop/mainapp/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=128, verbose_name='название', unique=True)
    description = models.TextField(verbose_name='описание')
    is_active = models.BooleanField(default=True, verbose_name='Активен')
    def __str__(self):
        return f'#{self.pk}. {self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('name', )

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория')
    name = models.CharField(max_length=128, verbose_name='название', unique=True)
    image = models.ImageField(upload_to='product', blank=True, null=True, verbose_name='изображение')
    short_desc = models.CharField(max_length=128, verbose_name='краткое описание')
    description = models.TextField(max_length=128, verbose_name=' полное описание')
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='цена')
    quantity =models.PositiveSmallIntegerField(default=0, verbose_name='количество')
    is_active = models.BooleanField(default=True, verbose_name='Активен')
    def __str__(self):
        return f'{self.name} ({self.category.name})'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

geekshop/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from mainapp.models import Product, Category
from basketapp.models import Basket
from mainapp.services import get_basket, get_same_products, get_hot_product




def index(request):
    context = {
        'products': Product.objects.all()[:4],
        'basket': get_basket(request.user)
    }
    return render(request, 'mainapp/index.html', context)
# Create your views here.

def products(request, pk=None):
    print(pk)
    links_menu = Category.objects.all()


    if pk is not None:
        if pk == 0:
            products_list = Product.objects.all()
            category_item = {'name' : 'все', 'pk' : 0}
        else:
            category_item = get_object_or_404(Category, pk=pk)
            products_list = Product.objects.filter(category_id=pk)

        context = {
            'links_menu' : links_menu,
            'products' : products_list,
            'category' : category_item,
            'basket' : get_basket(request.user)
              }
        return render(request, 'mainapp/products_list.html', context)


    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    context = {
        'links_menu': links_menu,
        'basket': get_basket(request.user),
        'hot_product': hot_product,  ####correct
        'same_products': same_products  ####correct
    }
    return render(request, 'mainapp/products.html', context)

def product(request, pk):
    product_item = get_object_or_404(Product, pk=pk)
    context = {
        'links_menu': Category.objects.all(),
        'product': product_item,
        'basket': get_basket(request.user),
    }
    return render(request, 'mainapp/product.html', context)

def contact(request):
    context = {
        'basket': get_basket(request.user)
    }
    return render(request, 'mainapp/contact.html')

geekshop/mainapp/templates/mainapp/base.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>{{ title|default:"My shop" }}</title>
	{% block css %}
        <link rel="stylesheet" type= "text/css" href="{% static 'css/style.css'%}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}

    {% block js %}
    {% endblock %}
</head>
<body>
	<div class="container">
		{% block menu %}
		{% endblock %}

		{% block content %}
		{% endblock %}



		<div class="clr"></div>

	</div>

    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017-{%now "Y"%}</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>

</body>
</html>

geekshop/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
		<div class="hero">
			<div class="header clearfix">
			{% include 'mainapp/includes/inc_main_menu.html' %}
			</div>
			<h1>наши контакты</h1>
		</div>
{% endblock %}

{% block content %}
		<div class="location">
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
		</div>
{% endblock %}

geekshop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block menu %}
		<div class="slider">
			<div class="header clearfix">
			{% include 'mainapp/includes/inc_main_menu.html' %}
			</div>
			<div class="text-slider">
				<h3 class="green">тенденции</h3>
				<h3 class="big"> удобные стулья</h3>
				<p>Новый уровень комфорта. Отличные характеристики.</p>
				<a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
			</div>	
			<div class="navi">
				<a href="#"></a><a href="#"></a><a href="#"></a>
			</div>
		</div>
{% endblock %}


{% block content %}
		<div class="featured">

			<div class="featured-menu">
					<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
			</div>
			<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
			<div class="clearfix">
			</div>
			<div class="tab-content">

				{% for product in products %}
				<div class="block">
					<a href="{% url 'products:product_item' product.pk %}"><img src="{% if product.image %} /media/{{ product.image}} {% else %} {% static 'img/product-1.jpg' %} {%endif%}" alt="">
						<div class="text">
							<img src="{% static 'img/icon-hover.png' %}" alt="img">
							<h4>{{ product.name }}</h4>
							<p>{{ product.short_desc }} </p>
						</div>
					</a>
				</div>
				{% endfor %}
			</div>
		</div>
{% endblock %}

geekshop/mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
		<div class="hero-white">
			<div class="header clearfix">
				{% include 'mainapp/includes/inc_main_menu.html' %}
			</div>
		</div>
{% endblock %}

{% block content %}
		<div class="details">
			<div class="links clearfix">
				{% include 'mainapp/includes/inc_products_menu.html' %}

			</div>

			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">

						<img src="/media/{{product.image }}">
					</div>
					<!--<div class="slider-control">
					<div class="block">
							<a href="#"><img src="/media/{{product.image }}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="/media/{{product.image }}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="/media/{{product.image }}" alt="">
								<div class="text"></div>
							</a>
						</div>
					</div>-->
				</div>

				<div class="description">
					<h3 class="big-bold">{{product.name}}</h3>
					<h3 class="red">{{ product.category.name }}</h3>
					<p class="price"> {{ product.price|floatformat:2 }} <span>руб</span></p>

					<a href="{% url 'basket:add' product.pk %}" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>

					<div class="description-text">
						<p>{{ product.short_desc }}</p>
						<p>{{ product.description }}</p>
					</div>
				</div>
			</div>
		</div>

{% endblock %}

geekshop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
		<div class="hero-white">
			<div class="header clearfix">
				{% include 'mainapp/includes/inc_main_menu.html' %}
			</div>
		</div>
{% endblock %}

{% block content %}
		<div class="details">
			<div class="links clearfix">
				{% include 'mainapp/includes/inc_products_menu.html' %}

			</div>

			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">

						<img src="/media/{{hot_product.image }}">
					</div>
					<!--<div class="slider-control">
					<div class="block">
							<a href="#"><img src="/media/{{hot_product.image }}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="/media/{{hot_product.image }}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="/media/{{hot_product.image }}" alt="">
								<div class="text"></div>
							</a>
						</div>
					</div>-->
				</div>

				<div class="description">
					<h3 class="big-bold">{{hot_product.name}}</h3>
					<h3 class="red">горячее предложение</h3>
					<p class="price"> {{ hot_product.price|floatformat:2 }} <span>руб</span></p>

					<a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>

					<div class="description-text">
						<p>{{ hot_product.short_desc }}</p>
					</div>
				</div>
			</div>

			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
				</div>
				<div class="related-products clearfix">
					{% for product in same_products%}
						<div class="block">
							<a href="{% url 'products:product_item' product.pk %}"><img src="/media/{{ product.image }}" alt="">
								<div class="text">
									<img src="{%static 'img/icon-hover.png' %}" alt="img">
									<h4>{{ product.name }}</h4>
									<p>{{ product.short_desc }}</p>
								</div>
							</a>
						</div>
					{% endfor %}
				</div>
			</div>
		</div>

{% endblock %}

geekshop/mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
		<div class="hero-white">
			<div class="header clearfix">
				{% include 'mainapp/includes/inc_main_menu.html' %}
			</div>
		</div>
{% endblock %}

{% block content %}
		<div class="details">
			<div class="links clearfix">
				{% include 'mainapp/includes/inc_products_menu.html' %}
			</div>

			<div class="products">
				<div class="title clearfix">
					<h2>
						Категория : {{ category.name|title }}
					</h2>
				</div>


				<div class="products">
					{% for product in products%}
						<div class="block">
							<a href="{% url 'products:product_item' product.pk %}"><img src="/media/{{ product.image }}" alt="">
								<div class="text">
									<img src="{% static 'img/icon-hover.png' %}" alt="img">
									<h4> {{ product.name }}</h4>
									<h4> {{ product.category.name }}</h4>
									<p> {{ product.short_desc}} </p>
								</div>
							</a>
						</div>
					{% endfor%}
				</div>

		</div>
{% endblock %}